### ISSUE TITLE
Changes in "uncrustify.cfg"

### ISSUE THREAD

**Issue by chintan1891** [RobotsAndPencils/objective-c-style-guide#11]
Hi,
I am following all your objective c guideline into my new project.
I am using "Uncrustify.cfg" into Uncrustify plugin.
At the time of using this config, i found that some of your guidelines are not followed using Uncrustify.

-Use one empty line between class extension and implementation in .m file. (Empty line is not automatically added)
-Don't put a space between an object type and the protocol it conforms to. (Extra space is not removed automatically)
-When using pragma marks leave 1 newline before and after. (New line not added after #pragma)

Below are some issues which i fixed myself.
-Always end a file with a newline.
	# Use "nl_end_of_file" = force & "nl_end_of_file_min" = 1

-Block based colon aligning not working
	#Use "indent_oc_block_msg" = 0

I have done these changes into my branch, if you need i can create a pull request. (https://github.com/chintan1891/objective-c-style-guide/blob/master/uncrustify.cfg)

**Comment by interstateone** [comment]
I know I'm replying _really_ late, but thanks for taking the time to let us know about this! If you're still able to create a pull request for these changes that would be great. It's a shame that Uncrustify doesn't seem to support some of our recommendations as you've mentioned.

**Comment by interstateone** [comment]
On second thought, I'll just make the change myself, it's pretty quick :smile:
